alter table EXTUSER_REQUEST_TAG add constraint FK_EXTUSER_REQUEST_TAG_REQUEST foreign key (REQUEST_ID) references EXTUSER_REQUEST(ID);
create index IDX_EXTUSER_REQUEST_TAG_REQUEST on EXTUSER_REQUEST_TAG (REQUEST_ID);
